    1 REM NOTE: Basic language type forced to be:
    2 REM       trs2 - TRS-80 Level II BASIC tokenized file
   10 CLS
   20 PRINT@273,"SUPER STAR TREK INSTRUCTIONS"
   30 PRINT@409,"COPYRIGHT BY"
   40 PRINT@534,"CREATIVE COMPUTING"
   50 PRINT@657,"MORRISTOWN, NEW JERSEY 07960"
   60 P=1:GOSUB1400
   70 CLS
   80 PRINT@320,"1. WHEN YOU SEE 'COMMAND ?' PRINTED, ENTER ONE OF THE LEGAL"
   90 PRINT"     COMMANDS (NAV,SRS,LRS,PHA,TOR,SHE,DAM,COM OR XXX)."
  100 GOSUB1450
  110 PRINT@320,"2. IF YOU SHOULD TYPE IN AN ILLEGAL COMMAND, YOU'LL GET A SHORT"
  120 PRINTTAB(12);"LIST OF THE LEGAL COMMANDS PRINTED OUT."
  130 GOSUB1450
  140 PRINT@192,"3. SOME COMMANDS REQUARE YHOU TO ENTER DATA (FOR EXAMPLE, THE"
  150 PRINT"      'NAV' COMMAND COMES BACK WITH 'CORSE (1-9) ?'.) IF YOU"
  160 PRINT"  TYPE IN ILLEGAL DATA (LIKE NEGATIVE NUMBERS), THAT COMMAND"
  170 PRINTTAB(22);"WILL BE ABORTED."
  180 GOSUB1450
  190 PRINT:PRINT
  200 PRINT"      THE GALAXY IS DIVIDED INTO AN 8 X 8 QUADRANT GRID,"
  210 PRINT"AND EACH QUADRANT IS FURTHER DIVIDED INTO AN 8 X 8 SECTOR GRID"
  220 PRINT
  230 PRINT"  YOU WIL BE ASSIGNED A STARTING POINT SOMEWHERE IN THE"
  240 PRINT"GALAXY TO BEGIN A TOUR OF DUTY AS COMMANDER OF THE STARSHIP"
  250 PRINT"/ENTERPRISE/; YOUR MISSION: TO SEEK AND DESTROY THE FLEET OF"
  260 PRINT"KLINGON WARSHIPS WHICH ARE MENACING THE UNITED FEDERATION OF"
  270 PRINT"PLANETS."
  280 GOSUB1450
  290 PRINT"  YOU HAVE THE FOLLOWING COMMANDS AVAILABLE TO YOU AS"
  300 PRINT"      CAPTAIN OF THE STARSHIP ENTERPRISE:"
  310 PRINT
  320 PRINT"/NAV/ COMMAND = WARP ENGINE CONTROL --"
  330 PRINT
  340 PRINT"  COURSE IS IN A CIRCULAR NUMERICAL       4  3  2"
  350 PRINT"		  VECTOR ARRANGEMENT AS SHOWN              . . ."
  360 PRINT"  INTERGER AND REAL VALUES MAY BE           ..."
  370 PRINT"  USED.  (THUS COURSE 1.5 IS HALF-      5 ---*--- 1"
  380 PRINT"      WAY BETWEEN 1 AND 2.                  ..."
  390 PRINT"                                           . . ."
  400 PRINT"VALUES MAY APPROACH 9.0, WHICH            6  7  8"
  410 PRINT"      ITSELF IS EQUIVALENT TO 1.0"
  420 PRINT"                                  COURSE"
  430 GOSUB1450
  440 PRINT@256,""
  450 PRINTTAB(15);"ONE WARP FACTOR IS THE SIZE OF"
  460 PRINTTAB(14);"ONE QUARDRANT.  THEREFORE, TO GET"
  470 PRINTTAB(13);"FROM QUARDRANT 6,5 TO 5,5 YOU WOULD"
  480 PRINTTAB(16);"USE COURSE 3, WARP FACTOR 1."
  490 GOSUB1450
  500 PRINT"/SRS/ COMMAND = SHORT RANGE SENSOR SCAN"
  510 PRINT
  520 PRINT"      SHOWS YOU A SCAN OF YOUR PRESENT QUARDRANT."
  530 PRINT
  540 PRINT"      SYMBLOGY ON YOUR SENSOR SCREEN IS AS FOLLOWS:"
  550 PRINT"      <*> = YOUR STARSHIP'S POSITTION"
  560 PRINT"      +K+ = KLINGON BATTLE CRUISER"
  570 PRINT"      >!< = FEDERATION STARBASE (REFUEL/REPAIR/RE-ARM HERE !"
  580 PRINT"  * = STAR"
  590 PRINT
  600 PRINT"      A CONDENSED 'STATUS REPORT' WILL ALSO BE PRESENTED."
  610 GOSUB1420
  620 PRINT"/LRS/ COMMAND = LONG RANGE SENSOR SCAN"
  630 PRINT
  640 PRINT"      SHOWS CONDITIONS IN SPACE FOR ONE QUADRANT ON EACH SIDE"
  650 PRINT"  OF THE ENTERPRISE (WHICH IS IN THE MIDDLE OF THE SCAN)."
  660 PRINT"  THE SCAN IS CODED IN THE FORM /###/, WHER THE UNITS DIGIT"
  670 PRINT"  IS THE NUMBER OF STARS, THE TENS DIGIT IS THE NUMBER OF"
  680 PRINT"  STARBASES, AND THE HUNDREDS DIGIT IS THE NUMBER OF"
  690 PRINT"  KLINGONS."
  700 PRINT
